# -*- coding: utf-8 -*-
"""Webscraper for WA State.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jl-8zsb1dWUCtTdUoYg8e8ghDZu9yp3g
"""

import requests
from bs4 import BeautifulSoup
import gspread
from oauth2client.service_account import ServiceAccountCredentials

from google.colab import auth
from google.auth import default
from gspread_dataframe import set_with_dataframe

# Authenticate google account
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# Web scraping
url = 'https://eds.ospi.k12.wa.us/iGrants/(S(fbwu4ds2hasvkiedofbe2rrn))/WebPages/HomePages/Allocations/Allocation.aspx?Type=State&Fp=23'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')
# Extract data from the table using BeautifulSoup

spreadsheet_name = "WA State Grant for 23-24"
worksheet_name = "Allocations State Funded for 23-24"

# Check if the spreadsheet already exists
existing_spreadsheet = None

#if spreadsheet exists, open it.
try:
    existing_spreadsheet = gc.open(spreadsheet_name)
    print(f"Spreadsheet '{spreadsheet_name}' already exists.")
#if spreadsheet does not exists, create a new spreadsheet.
except gspread.SpreadsheetNotFound:
    print(f"Spreadsheet '{spreadsheet_name}' not found. Creating a new one...")
    existing_spreadsheet = gc.create(spreadsheet_name)

# Check if the worksheet already exists
try:
    worksheet = existing_spreadsheet.worksheet(worksheet_name)
    print(f"Tab '{worksheet_name}' already exists.")
except gspread.WorksheetNotFound:
    # If it doesn't exist, create a new worksheet
    print(f"Tab '{worksheet_name}' not found. Creating a new one...")
    worksheet = existing_spreadsheet.add_worksheet(title=worksheet_name, rows=1, cols=1)

# Extract data from the soup object (replace this with your own logic)
data_to_append = []
for row in soup.find_all('tr'):
    cells = row.find_all('td')
    row_data = [cell.text for cell in cells]
    data_to_append.append(row_data)

# Append data to the Google Sheet
worksheet.append_rows(data_to_append, value_input_option='RAW')

# delete unused tab named 'Sheet1'
try:
  # Get the worksheet by name
  print('Deleting Sheet1...')
  worksheet_to_delete = existing_spreadsheet.worksheet('Sheet1')

  # Delete the worksheet
  existing_spreadsheet.del_worksheet(worksheet_to_delete)
except gspread.WorksheetNotFound:
  print('Sheet1 not found. Finalizing Spreadsheet...')

start_row = 1
end_row = 4

# Delete rows
worksheet.delete_rows(start_row, end_row)

print("Worksheets created and populated successfully.")
print(f"https://docs.google.com/spreadsheets/d/{existing_spreadsheet.id}")